Repository ImpressCMS/impresscms, pull requests merged in 2018-07, with the labels that each got.

#304 Added some new icons to readme
  README.md
Labels: enhancement

#308 Update README.md
  README.md
Labels: enhancement

#313 Better composer requirements versions for composer.json
  composer.json
Labels: composer, enhancement

#268 $xoopsMailer -> $mailer
  invite.php
  libraries/icms/data/notification/Object.php
  libraries/icms/ipf/member/Handler.php
  libraries/icms/member/user/Object.php
  lostpass.php
  misc.php
  modules/system/admin/mailusers.php
  pmlite.php
  register.php
  resetpass.php
Labels: enhancement

#133 Move php downloader to composer
  composer.json
  libraries/icms/file/TarDownloader.php
  libraries/icms/file/TarFileHandler.php
  libraries/icms/file/ZipDownloader.php
  libraries/icms/file/ZipFileHandler.php
  modules/system/admin/tplsets.php
  tests/libraries/icms/FilesTest.php
Labels: bug, composer, enhancement

#174 Rss is generated with composer lib
  composer.json
  libraries/icms/feeds/Rss.php
  modules/system/icms_version.php
  modules/system/templates/system_rss.html
Labels: composer, enhancement

#312 Code Climate instead of Scrutinizer
  .codeclimate.yml
  .scrutinizer.yml
  .travis.yml
Labels: infrastructure
