Repository ImpressCMS/impresscms, pull requests merged in 2019-12, with the labels that each got.

#566 Removed installation_notify
  htdocs/libraries/icms/module/Handler.php
  htdocs/modules/system/admin/modulesadmin/modulesadmin.php
  htdocs/modules/system/include/update-13.php
Labels: bug, enhancement

#549 Removed many deprecations
  htdocs/editors/CKeditor/xoops_version.php
  htdocs/editors/tinymce/icms_version.php
  include/functions.php
  include/xoopscodes.php
  libraries/icms.php
  libraries/icms/core/Object.php
  libraries/icms/core/Textsanitizer.php
  libraries/icms/form/Base.php
  libraries/icms/form/Simple.php
  libraries/icms/ipf/Handler.php
  libraries/icms/ipf/Object.php
  libraries/icms/ipf/category/Object.php
  libraries/icms/ipf/seo/Object.php
  libraries/icms/member/user/Object.php
  libraries/icms/properties/Handler.php
  libraries/icms/view/block/Handler.php
  readpmsg.php
  tests/libraries/icms/FormTest.php
  tests/libraries/icms/IPFTest.php
  tests/libraries/icms/ViewTest.php
Labels: enhancement

#529 Fixed installer collation selection
  htdocs/install/install_tpl.php
  htdocs/install/page_dbsettings.php
  htdocs/install/prototype.js
Labels: bug

#571 Move prototype inclusion so trust_path creation works fixes #569
  htdocs/install/install_tpl.php
  htdocs/install/page_dbsettings.php
Labels: bug

#572 core theme as default
  htdocs/install/makedata.php
Labels: enhancement

#577 Adding quotes around column and index names for MySQL 8 compatibility.
  htdocs/install/sql/mysql.structure.sql
Labels: installer
