Repository ImpressCMS/impresscms, pull requests merged in 2019-10, with the labels that each got.

#504 make expiration header dynamic in the past
  htdocs/footer.php
Labels: bug

#505 Update php requirements to 5.6
  htdocs/install/language/english/install.php
  htdocs/install/language/francais/install.php
  htdocs/install/language/italiano/install.php
Labels: enhancement, installer

#507 PHP7 improvements based on mamba7x PR
  htdocs/install/class/mainfilemanager.php
  htdocs/install/class/settingmanager.php
  htdocs/install/class/textsanitizer.php
  htdocs/libraries/icms/form/Base.php
Labels: PHP7, bug

#512 Fixed function signatures in icms_image_Handler (1.4)
  htdocs/libraries/icms/image/Handler.php
Labels: bug

#510 Fixed suppressed warning if variable $options['folderName'] is undefined or empty when creating theme (1.4.x)
  htdocs/libraries/icms/view/theme/Factory.php
Labels: bug, enhancement

#511 Fixed bug for possible warning that $options['folderName'] is undefined (2.0.x)
  libraries/icms/view/theme/Factory.php
Labels: bug

#518 Aura session is used for handling sessions
  composer.json
  composer.lock
  core/providers/LoggerServiceProvider.php
  core/providers/PreloadServiceProvider.php
  core/providers/SessionServiceProvider.php
  edituser.php
  finish_auth.php
  footer.php
  include/checklogin.php
  include/common.php
  include/functions.php
  libraries/icms.php
  libraries/icms/auth/method/Ldap.php
  libraries/icms/auth/method/Local.php
  libraries/icms/core/Security.php
  libraries/icms/core/Session.php
  libraries/icms/form/elements/Hiddentoken.php
  libraries/icms/form/elements/captcha/ImageHandler.php
  libraries/icms/form/elements/captcha/Object.php
  libraries/icms/form/elements/captcha/Text.php
  libraries/icms/member/Handler.php
  libraries/icms/member/user/Object.php
  libraries/icms/response/HTML.php
  libraries/icms/view/PageBuilder.php
  libraries/icms/view/block/Object.php
  libraries/icms/view/theme/Factory.php
  plugins/preloads/autologin.php
  plugins/preloads/multilanguage.php
  plugins/preloads/userinfo.php
  plugins/textsanitizer/hiddencontent/hiddencontent.php
  session_confirm.php
  tests/libraries/icms/SessionTest.php
  user.php
Labels: enhancement
