Repository ImpressCMS/impresscms, pull requests merged in 2019-05, with the labels that each got.

#406 added slack button
  README.md
Labels: enhancement, infrastructure

#413 disabled the camelcase check
  .codeclimate.yml
Labels: Code Climate

#420 Start 1.4.0 cycle
  htdocs/include/version.php
  htdocs/modules/system/icms_version.php
Labels: PHP7

#419 Update icms13 installer for php7
  htdocs/include/common.php
  htdocs/install/class/dbmanager.php
  htdocs/install/page_dbconnection.php
  htdocs/install/page_dbsettings.php
  htdocs/install/page_modulesinstall.php
  htdocs/libraries/icms/core/DataFilter.php
Labels: PHP7

#412 This probably will fix #295 issue
  .gitignore
  Homestead.yaml
  admin.php
  composer.json
  composer.lock
  core/providers/ModuleServiceProvider.php
  htdocs/index.php
  htdocs/install/common.inc.php
  htdocs/install/makedata.php
  htdocs/install/page_modulesinstall.php
  include/common.php
  include/constants.php
  include/cp_functions.php
  include/cp_header.php
  include/functions.php
  libraries/icms.php
  libraries/icms/ipf/Handler.php
  libraries/icms/view/block/Handler.php
  mainfile.php
  modules/system/admin/modules/modules.php
  modules/system/admin/preferences.php
  modules/system/autotask.php
  user.php
Labels: bug, composer, enhancement

#443 This probably will fix good enough #367 issue (1.4)
  htdocs/libraries/icms/member/groupperm/Handler.php
Labels: bug

#438 upgraded jquery to 3.4.0 (for 1.4.0)
  htdocs/libraries/jquery/jquery.js
Labels: bug

#452 Update Textsanitizer.php
  htdocs/libraries/icms/core/Textsanitizer.php
  htdocs/libraries/icms/form/Element.php
  htdocs/plugins/preloads/autologin.php
Labels: bug

#451 required missing is blocking error
  htdocs/libraries/icms/core/Object.php
Labels: bug

#453 removed many unused now disallows from robots.txt file
  htdocs/robots.txt
Labels: bug, enhancement

#456 fixed pre-release badge, license link, travis badge branch
  README.md
Labels: bug

#457 changed badges links in readme for 1.4 instead of master
  README.md
Labels: bug, enhancement

#417 Added env function
  composer.json
  composer.lock
  htdocs/install/class/dbmanager.php
  htdocs/install/modulesadmin.php
  htdocs/install/page_tablescreate.php
  htdocs/install/page_tablesfill.php
  include/constants.php
  libraries/icms/auth/method/Ldap.php
  libraries/icms/core/Logger_render.php
  libraries/icms/core/Password.php
  libraries/icms/core/Security.php
  libraries/icms/core/Session.php
  libraries/icms/db/Factory.php
  libraries/icms/db/legacy/mysql/Database.php
  libraries/icms/db/legacy/mysql/Utility.php
  libraries/icms/db/legacy/updater/Handler.php
  libraries/icms/db/legacy/updater/Table.php
  libraries/icms/view/block/Object.php
  mainfile.php
  modules/system/admin/modules/modules.php
  tests/bootstrap.php
  tests/core/MainfileTest.php
Labels: enhancement
