Repository ImpressCMS/impresscms, pull requests merged in 2019-07, with the labels that each got.

#471 successful upgrading now updates version info
  htdocs/modules/system/include/update.php
Labels: bug

#467 Smarty upgrade for 1.4
  htdocs/install/class/index.html
  htdocs/install/include/index.html
  htdocs/install/index.html
  htdocs/install/language/index.html
  htdocs/install/pathsettings.js
  htdocs/install/sql/index.html
  htdocs/libraries/smarty/Config_File.class.php
  htdocs/libraries/smarty/Smarty.class.php
  htdocs/libraries/smarty/Smarty_Compiler.class.php
  htdocs/libraries/smarty/internals/core.assemble_plugin_filepath.php
  htdocs/libraries/smarty/plugins/function.math.php
Labels: PHP7, bug, dependencies, enhancement

#483 PHP7 Fix to replace continue with break in cleanvar
  htdocs/libraries/icms/core/Object.php
Labels: PHP7, bug
