Repository ImpressCMS/impresscms, pull requests merged in 2019-11, with the labels that each got.

#513 Fixed function signatures in icms_image_Handler (2.0)
  libraries/icms/image/Handler.php
Labels: bug

#516 Removed get results by reference where is not needed in modules/system/admin/images/images.php (2.0)
  modules/system/admin/images.php
Labels: bug

#520 icms::handler now use container functionality
  libraries/icms.php
Labels: enhancement

#502 Added iconv polyfill when such extension doesn't exist
  composer.json
  composer.lock
Labels: composer, enhancement

#536 Removed old XML classes
  composer.lock
  libraries/xml/rpc/bloggerapi.php
  libraries/xml/rpc/metaweblogapi.php
  libraries/xml/rpc/movabletypeapi.php
  libraries/xml/rpc/xmlrpcapi.php
  libraries/xml/rpc/xmlrpcparser.php
  libraries/xml/rpc/xmlrpctag.php
  libraries/xml/rpc/xoopsapi.php
  libraries/xml/rss/xmlrss2parser.php
  libraries/xml/saxparser.php
  libraries/xml/themesetparser.php
  libraries/xml/xmltaghandler.php
Labels: enhancement

#528 Fixed PathStuffController's constructor
  htdocs/install/page_pathsettings.php
Labels: bug

#538 Added support section into composer.json
  composer.json
Labels: composer, enhancement

#542 Removed icms_get_base_domain and icms_get_url_domain
  include/functions.php
Labels: enhancement

#530 curl extension in installer now is requirement not optional
  htdocs/install/page_modcheck.php
Labels: bug, installer

#545 Added 'stale' github action
  .github/workflows/stale.yml
Labels: enhancement, infrastructure

#544 Use newer CodeClimate test reporter
  .travis.yml
  composer.json
  composer.lock
  include/constants.php
Labels: Code Climate, enhancement, infrastructure

#540 added keywords section to composer.json
  composer.json
Labels: composer, enhancement

#543 Added index.html for those who fails to place ImpressCMS files in correct folders
  index.html
Labels: bug, enhancement

#541 Readme style updated
  README.md
Labels: enhancement

#539 Added homepage to composer.json
  composer.json
Labels: composer, enhancement

#535 Composer files updated to pass composer validate most rules
  composer.json
  composer.lock
Labels: bug, composer

#509 Remove admin template folder in system module on upgrade
  htdocs/modules/system/include/update.php
Labels: bug

#527 Use Aura.SQL for database operations
  composer.json
  composer.lock
  core/providers/DatabaseServiceProvider.php
  htdocs/install/class/dbmanager.php
  htdocs/install/common.inc.php
  htdocs/install/install_tpl.php
  htdocs/install/language/english/makedata.php
  htdocs/install/language/english/mysql.lang.data.sql
  htdocs/install/makedata.php
  htdocs/install/page_dbconnection.php
  htdocs/install/page_dbsettings.php
  htdocs/install/page_tablesfill.php
  htdocs/install/prototype.js
  htdocs/install/sql/mysql.data.sql
  include/cp_functions.php
  libraries/icms/db/Connection.php
  libraries/icms/db/Factory.php
  libraries/icms/db/IConnection.php
  libraries/icms/db/IDatabase.php
  libraries/icms/db/legacy/Database.php
  libraries/icms/db/legacy/Factory.php
  libraries/icms/db/legacy/PdoDatabase.php
  libraries/icms/db/legacy/mysql/Database.php
  libraries/icms/db/legacy/mysql/Proxy.php
  libraries/icms/db/legacy/mysql/Safe.php
  libraries/icms/db/legacy/updater/Handler.php
  libraries/icms/db/mysql/Connection.php
Labels: composer, enhancement

#534 Updated jquery to 3.4.1
  htdocs/libraries/jquery/jquery.js
  htdocs/themes/core/js/index.html
Labels: security vulnerability

#533 Bootstrap upgraded to 3.4.1
  htdocs/libraries/bootstrap/bootstrap.min.css
  htdocs/libraries/bootstrap/bootstrap.min.css.map
  htdocs/libraries/bootstrap/bootstrap.min.js
Labels: security vulnerability

#531 curl is now requirement in installer not recommended extension + fixed extensions check icons
  htdocs/install/page_modcheck.php
Labels: bug, installer

#546 Removing wideimage directories and files
  libraries/wideimage/index.html
  libraries/wideimage/lib/Font/index.html
  libraries/wideimage/lib/Mapper/index.html
  libraries/wideimage/lib/Operation/index.html
  libraries/wideimage/lib/index.html
  libraries/wideimage/lib/vendor/JPEXS/index.html
  libraries/wideimage/lib/vendor/de77/index.html
  libraries/wideimage/lib/vendor/index.html
Labels: bug

#548 Fixed installation messages after moving to aura.sql
  htdocs/install/makedata.php
Labels: bug

#547 Removed special SSL login functionality
  htdocs/install/makedata.php
  htdocs/themes/core/modules/system/system_userform.html
  modules/system/blocks/system_blocks.php
  modules/system/language/english/admin/preferences.php
  modules/system/templates/blocks/system_block_login.html
Labels: enhancement

#560 Remove XOOPS_XMLRPC check from constants file
  include/constants.php
Labels: enhancement

#559 Fixes all places where was XOOPS_GROUP_* constants left
  finish_auth.php
  htdocs/editors/tinymce/jscripts/plugins/xoopsimagemanager/xoopsimagebrowser.php
  libraries/icms/auth/stores/local.php
  libraries/icms/form/elements/captcha/Object.php
  libraries/icms/form/elements/select/Image.php
  modules/system/admin/comments/admin_header.php
  modules/system/admin/modules/modules.php
  modules/system/admin/users/userform.php
  modules/system/blocks/system_admin_blocks.php
  modules/system/blocks/system_blocks.php
  register.php
  search.php
  user.php
  userinfo.php
Labels: bug

#555 Deprecated warnings made into @deprecated comments in database connection class
  libraries/icms/db/Connection.php
Labels: enhancement

#558 Fixes getting url in controller component
  libraries/icms/ipf/Controller.php
Labels: bug

#557 Fixed many url warnings in IPF Table component
  libraries/icms/ipf/view/Table.php
Labels: bug
