Repository ImpressCMS/impresscms, pull requests merged in 2019-04, with the labels that each got.

#392 Added whitesource integration support
  .whitesource
Labels: infrastructure

#393 Create .whitesource in 1.3.x branch
  .whitesource
Labels: infrastructure

#396 Update Handler.php
  htdocs/libraries/icms/module/Handler.php
Labels: bug

#397 renamed branches in readme: retro -> master
  README.md
Labels: infrastructure

#367 Update Group permission Handler.php for strict PHP
  htdocs/libraries/icms/member/groupperm/Handler.php
Labels: enhancement

#400 no restylizer for 1.3.x branch
  .restyled.yaml
Labels: infrastructure
