Repository ImpressCMS/impresscms, pull requests merged in 2020-12, with the labels that each got.

#815 Better sanitize database queries in installer
  htdocs/install/page_dbsettings.php
Labels: bug

#812 Prevents using submitted filenames with ../ for controller
  htdocs/libraries/icms/ipf/Controller.php
Labels: bug, security vulnerability

#821 Fixed possible file system exposing due language cookie on installer (reported by hackerone_success)
  htdocs/install/common.inc.php
Labels: bug, security vulnerability

#823 Temp fix: use composer v1.0 for tests
  .github/workflows/test.yml
Labels: composer, infrastructure

#721 Removed checkSuperGlobals from Security class
  core/Providers/SecurityServiceProvider.php
  core/Security/RequestSecurity.php
  tests/libraries/icms/SecurityTest.php
Labels: enhancement

#836 Limit maximum length of password
  htdocs/include/checklogin.php
  htdocs/include/registerform.php
  htdocs/modules/system/templates/system_userform.html
  htdocs/register.php
Labels: security vulnerability

#822 Fixed possible file system exposing due language cookie on installer (reported by hackerone_success)
  htdocs/install/class/xoopsinstallwizard.php
Labels: bug, security vulnerability

#813 Prevents using submitted filenames with ../ for modelcontroller
  core/ModelController.php
Labels: bug, security vulnerability

#798 Fixed short if bug for newer PHP in BlockHandler
  core/Models/BlockHandler.php
Labels: bug

#735 Removes textsanitizer plugins and default DHTMLEditor
  composer.json
  core/DataFilter.php
  core/View/Form/Elements/DHTMLTextAreaElement.php
  include/comment_new.php
  include/comment_reply.php
  include/functions.php
  migrations/20200806213927_convert_all_textsanitizers_contents_to_h_t_m_l.php
  migrations/20200806214630_remove_settings_to_make_possible_to_use_old_style_d_h_t_m_l_editor.php
  migrations/20200807225033_remove_use_w_y_s_i_w_y_g_editor_right.php
  modules/system/admin/groups.php
  modules/system/admin/groups/groupform.php
  modules/system/admin/groups/groups.php
  modules/system/language/english/admin/preferences.php
  plugins/textsanitizer/hashtags/hashtags.js
  plugins/textsanitizer/hashtags/hashtags.php
  plugins/textsanitizer/hashtags/hashtags.png
  plugins/textsanitizer/hiddencontent/hiddencontent.css
  plugins/textsanitizer/hiddencontent/hiddencontent.js
  plugins/textsanitizer/hiddencontent/hiddencontent.php
  plugins/textsanitizer/mentions/mentions.js
  plugins/textsanitizer/mentions/mentions.php
  plugins/textsanitizer/mentions/mentions.png
  plugins/textsanitizer/syntaxhighlightcss/css.png
  plugins/textsanitizer/syntaxhighlightcss/syntaxhighlightcss.css
  plugins/textsanitizer/syntaxhighlightcss/syntaxhighlightcss.js
  plugins/textsanitizer/syntaxhighlightcss/syntaxhighlightcss.php
  plugins/textsanitizer/syntaxhighlighthtml/html.png
  plugins/textsanitizer/syntaxhighlighthtml/syntaxhighlighthtml.css
  plugins/textsanitizer/syntaxhighlighthtml/syntaxhighlighthtml.js
  plugins/textsanitizer/syntaxhighlighthtml/syntaxhighlighthtml.php
  plugins/textsanitizer/syntaxhighlightjs/js.png
  plugins/textsanitizer/syntaxhighlightjs/syntaxhighlightjs.css
  plugins/textsanitizer/syntaxhighlightjs/syntaxhighlightjs.js
  plugins/textsanitizer/syntaxhighlightjs/syntaxhighlightjs.php
  plugins/textsanitizer/syntaxhighlightphp/php.png
  plugins/textsanitizer/syntaxhighlightphp/syntaxhighlightphp.css
  plugins/textsanitizer/syntaxhighlightphp/syntaxhighlightphp.js
  plugins/textsanitizer/syntaxhighlightphp/syntaxhighlightphp.php
  plugins/textsanitizer/wiki/wiki.js
  plugins/textsanitizer/wiki/wiki.php
  plugins/textsanitizer/wiki/wiki.png
  plugins/textsanitizer/wmp/wmp.gif
  plugins/textsanitizer/wmp/wmp.js
  plugins/textsanitizer/wmp/wmp.php
  plugins/textsanitizer/youtube/youtube.gif
  plugins/textsanitizer/youtube/youtube.js
  plugins/textsanitizer/youtube/youtube.php
  tests/libraries/icms/FormTest.php
Labels: composer, enhancement

#739 Replaced DB_SALT env variable with APP_KEY
  .env.example
  .github/packages/docker/nginx-php/Dockerfile
  .github/packages/docker/nginx-php/bin/entrypoint.sh
  .github/packages/docker/nginx-php/etc/php7/php-fpm.d/www.conf
  .github/workflows/test.yml
  .github/workflows/update-wiki.yml
  composer.json
  composer.lock
  core/Commands/GenerateAppKeyCommand.php
  core/Models/Block.php
  core/Security/Password.php
  htdocs/install/language/english/install.php
  htdocs/install/page_dbsettings.php
  htdocs/install/style.css
  htdocs/install/style_rtl.css
  htdocs/install/stylelight.css
  htdocs/install/stylelight_rtl.css
  lostpass.php
  plugins/smarty/resource.db.php
Labels: enhancement

#720 Using FireWall middleware for bad ips checking instead of Security class
  .github/workflows/test.yml
  composer.json
  composer.lock
  core/Extensions/ComposerDefinitions/RoutesComposerDefinition.php
  core/Providers/SecurityServiceProvider.php
  core/Security/RequestSecurity.php
  tests/libraries/icms/SecurityTest.php
Labels: composer, enhancement

#726 Removed old style redirect
  include/functions.php
  migrations/20200803205508_remove_use_custom_redirection_config_option.php
  modules/system/icms_version.php
  modules/system/language/english/admin/preferences.php
  modules/system/templates/system_redirect.html
Labels: enhancement

#737 Fixed 'Rename using the proper naming convention (this is a public var)' for #731
  core/ModelController.php
  core/Models/AbstractExtendedHandler.php
  core/Models/AbstractExtendedModel.php
  core/Models/CategoryHandler.php
  core/ObjectRegistry.php
  core/View/Table/Table.php
  modules/system/class/RatingHandler.php
Labels: bug, enhancement

#746 Messengers fields from user settings where removed
  core/Models/User.php
  edituser.php
  include/findusers.php
  language/english/user.php
  migrations/20200821223712_remove_old_messangers_from_user_if_exists.php
  modules/system/language/english/admin/users.php
  userinfo.php
Labels: bug, enhancement

#727 Timers visible as Server-Timing header (using HTTP Middleware)
  composer.json
  composer.lock
  core/Extensions/ComposerDefinitions/RoutesComposerDefinition.php
  core/Logger.php
  tests/libraries/icms/LoggerTest.php
Labels: composer, enhancement

#740 Encrypt cookies automatically with middleware if such preference is set
  composer.json
  composer.lock
  core/Extensions/ComposerDefinitions/RoutesComposerDefinition.php
  migrations/20200809205407_add_encrypt_cookies_settings_option.php
  modules/system/language/english/admin/preferences.php
Labels: composer, enhancement

#742 Added Roave Security Advisories to composer [dev]
  composer.json
  composer.lock
Labels: composer, dependencies, enhancement

#747 Removed some old openid related code + migration to update openid related fields
  composer.json
  core/Models/User.php
  edituser.php
  libraries/icms/auth/Object.php
  migrations/20200821235126_remove_open_i_d_field_from_config.php
  user.php
  userinfo.php
Labels: bug, enhancement

#838 Remove whitesource config
  .whitesource
Labels: bug, enhancement

#837 Remove whitesource config
  .whitesource
Labels: bug, infrastructure

#736 Fixed #733: Rename using the proper naming convention (This is a public var)
  core/ModelController.php
  core/Models/AbstractExtendedHandler.php
  core/Models/AbstractExtendedModel.php
  plugins/smarty/resource.db.php
Labels: bug, enhancement

#738 Use league/mime-type-detection for dealing with mimetype detection & deprecated icms_Utils
  composer.json
  composer.lock
  core/File/MediaUploader.php
  core/Providers/FilesystemServiceProvider.php
  core/Utils.php
  language/english/uploader.php
  migrations/20200808234213_remove_mime_type_editing.php
  modules/system/admin/mimetype.php
  modules/system/admin/mimetype/icms_version.php
  modules/system/admin/mimetype/images/mimetype.png
  modules/system/admin/mimetype/images/mimetype_big.png
  modules/system/admin/mimetype/images/mimetype_small.png
  modules/system/class/Mimetype.php
  modules/system/class/MimetypeHandler.php
  modules/system/language/english/admin/mimetype.php
Labels: composer, enhancement

#801 Added new translator service
  composer.json
  composer.lock
  core/Providers/TranslatorServiceProvider.php
Labels: enhancement

#745 Using properties instead of setVar when setting database object properties everywhere where is possible
  core/Database/Legacy/Updater/DatabaseUpdater.php
  core/Extensions/SetupSteps/Module/Install/AutotasksSetupStep.php
  core/Extensions/SetupSteps/Module/Install/BlockSetupStep.php
  core/Extensions/SetupSteps/Module/Install/ConfigSetupStep.php
  core/Extensions/SetupSteps/Module/Install/ViewTemplateSetupStep.php
  core/Extensions/SetupSteps/Module/Update/AutotasksSetupStep.php
  core/Extensions/SetupSteps/Module/Update/BlocksSetupStep.php
  core/Extensions/SetupSteps/Module/Update/ConfigSetupStep.php
  core/Extensions/SetupSteps/Module/Update/ViewTemplateSetupStep.php
  core/Facades/Config.php
  core/Facades/Member.php
  core/Messaging/MessageSender.php
  core/ModelController.php
  core/Models/AbstractExtendedModel.php
  core/Models/BlockHandler.php
  core/Models/BlockPositionHandler.php
  core/Models/Category.php
  core/Models/GroupPermHandler.php
  core/Models/Module.php
  core/Models/ModuleHandler.php
  core/Models/Notification.php
  core/Models/NotificationHandler.php
  core/Models/User.php
  edituser.php
  include/checklogin.php
  include/comment_delete.php
  include/comment_post.php
  include/rating.rate.php
  libraries/icms/auth/method/ldap/Provisioning.php
  libraries/image-editor/image-edit.php
  modules/system/admin/adsense.php
  modules/system/admin/autotasks.php
  modules/system/admin/avatars.php
  modules/system/admin/blocks.php
  modules/system/admin/customtag.php
  modules/system/admin/groupperm.php
  modules/system/admin/groups.php
  modules/system/admin/images.php
  modules/system/admin/images/browser.php
  modules/system/admin/pages.php
  modules/system/admin/tplsets.php
  modules/system/admin/userrank.php
  modules/system/admin/users.php
  modules/system/admin/users/users.php
  modules/system/class/AdsenseHandler.php
  modules/system/class/Autotasks.php
  modules/system/class/BlocksHandler.php
  modules/system/class/PagesHandler.php
  plugins/preloads/autologin.php
  pmlite.php
  register.php
Labels: enhancement

#749 Replace "ICMS_URL . '/modules/' -> ICMS_MODULES_URL . '/'" and "ICMS_ROOT_PATH . '/modules/' -> ICMS_MODULES_PATH . '/'"
  content.php
  core/Models/Block.php
  core/Models/Module.php
  include/functions.php
Labels: enhancement

#826 Upgraded middlewares/referrer-spam to 2.0.2 for PHP 8.0 and Composer 2.0 supporr
  composer.json
  composer.lock
Labels: bug, composer, enhancement

#750 System waiting block is now can be expanded with services defined in container
  composer.json
  modules/system/Extensions/WaitingInfoGetter/CommentsWaitingInfoGetter.php
  modules/system/Extensions/WaitingInfoGetter/InactiveUsersWaitingInfoGetter.php
  modules/system/Extensions/WaitingInfoGetterInterface.php
  modules/system/blocks/system_waiting.php
  plugins/index.html
  plugins/waiting/.gitignore
  plugins/waiting/.htaccess
  plugins/waiting/system.php
Labels: enhancement

#752 Smarty plugins can now be defined as services in container
  composer.json
  composer.lock
  core/Extensions/Smarty/Compiler/ForeachqCloseCompiler.php
  core/Extensions/Smarty/Compiler/ForeachqCompiler.php
  core/Extensions/Smarty/Compiler/IncludeqCompiler.php
  core/Extensions/Smarty/Compiler/XOAppUrlCompiler.php
  core/Extensions/Smarty/Compiler/XOImgUrlCompiler.php
  core/Extensions/Smarty/Functions/ResizeImageFunction.php
  core/Extensions/Smarty/Functions/XOInboxCountFunction.php
  core/Extensions/Smarty/Functions/XOPageNavFunction.php
  core/Extensions/Smarty/Functions/XoopsLinkFunction.php
  core/Extensions/Smarty/Modifiers/DebugPrintVarModifier.php
  core/Extensions/Smarty/Resource/DBResource.php
  core/Extensions/Smarty/SmartyCompilerExtensionInterface.php
  core/Extensions/Smarty/SmartyExtensionInterface.php
  core/Extensions/Smarty/SmartyFunctionExtensionInterface.php
  core/Extensions/Smarty/SmartyModifierExtensionInterface.php
  core/View/Template.php
  plugins/smarty/compiler.foreachq.php
  plugins/smarty/compiler.includeq.php
  plugins/smarty/function.resized_image.php
  plugins/smarty/function.xoInboxCount.php
  plugins/smarty/function.xoPageNav.php
  plugins/smarty/modifier.debug_print_var.php
Labels: composer, enhancement

#768 Added possibility to load modules definitions from different type of info files (like icms_version.php or composer.json)
  composer.json
  core/Exceptions/UndefinedVariableException.php
  core/Extensions/ExtensionDescriber/ExtensionDescriberInterface.php
  core/Extensions/ExtensionDescriber/Module/ImpressCMSComposerModuleDescriber.php
  core/Extensions/ExtensionDescriber/Module/ImpressCMSVersionModuleDescriber.php
  core/Models/Module.php
Labels: composer, enhancement

#770 Added possibility to describe themes (also support for composer themes!)
  composer.json
  core/Extensions/ExtensionDescriber/Theme/ImpressCMSComposerThemeDescriber.php
  core/Extensions/ExtensionDescriber/Theme/ImpressCMSLegacyThemeDescriber.php
  core/Models/TemplateFileHandler.php
  core/View/Theme/ThemeFactory.php
  htdocs/themes/core/composer.json
  htdocs/themes/iTheme/composer.json
Labels: composer, enhancement

#843 Fix the amount of cookies
  htdocs/libraries/icms/ipf/view/Table.php
Labels: bug

#842 Fixed bug with too long cookie names for Table component
  core/View/Table/Table.php
Labels: bug

#844 Fixed null response bug for root path instalations
  htdocs/index.php
Labels: bug

#848 Cleanup deprecated functions in functions.php
  htdocs/include/functions.php
  htdocs/install/class/settingmanager.php
  htdocs/invite.php
  htdocs/misc.php
Labels: enhancement

#849 Fixed includeq not working in smarty anymore bug
  core/Extensions/Smarty/Compiler/IncludeqCompiler.php
Labels: bug

#723 Session moved from container to middleware + theme changing now from HTTP middleware
  Homestead.yaml
  composer.json
  composer.lock
  core/Extensions/ComposerDefinitions/RoutesComposerDefinition.php
  core/Extensions/Smarty/Functions/XOInboxCountFunction.php
  core/Middlewares/ChangeThemeMiddleware.php
  core/Middlewares/SetSessionCookieConfigMiddleware.php
  core/Middlewares/UserMiddleware.php
  core/Models/User.php
  core/Providers/SessionServiceProvider.php
  core/Response/ViewResponse.php
  core/Security/RequestSecurity.php
  core/View/Form/Elements/Captcha/Image.php
  core/View/Form/Elements/Captcha/ImageRenderer.php
  core/View/Form/Elements/Captcha/TextMode.php
  core/View/Theme/ThemeFactory.php
  edituser.php
  footer.php
  htdocs/index.php
  include/checklogin.php
  include/common.php
  include/functions.php
  libraries/icms.php
  libraries/icms/auth/method/Ldap.php
  plugins/preloads/autologin.php
  plugins/preloads/multilanguage.php
  plugins/preloads/userinfo.php
  session_confirm.php
  tests/libraries/icms/SecurityTest.php
  user.php
Labels: enhancement

#851 Code Climate steps are now not required in GitLabCI test action
  .github/workflows/test.yml
Labels: infrastructure

#724 Code about multi_login moved from common.php into separate HTTP Middlware
  composer.lock
  core/Extensions/ComposerDefinitions/RoutesComposerDefinition.php
  core/Middlewares/MultiLoginOnlineInfoUpdaterMiddleware.php
  core/Providers/ConfigServiceProvider.php
  include/common.php
  tests/libraries/icms/SecurityTest.php
Labels: enhancement

#725 Site closed view functionality as dynamic SiteClosedMiddleware
  core/Extensions/ComposerDefinitions/RoutesComposerDefinition.php
  core/Middlewares/ChangeThemeMiddleware.php
  core/Middlewares/SiteClosedMiddleware.php
  core/Response/ViewResponse.php
  include/common.php
  include/site-closed.php
Labels: enhancement

#852 anti-clickjacking
  htdocs/footer.php
  htdocs/include/cp_functions.php
  htdocs/include/functions.php
Labels: security vulnerability
