Repository ImpressCMS/impresscms, pull requests merged in 2020-10, with the labels that each got.

#779 Added 'Security Policy' file
  SECURITY.md
Labels: enhancement, infrastructure

#781 Replace | to ||
  modules/system/admin/tplsets.php
Labels: bug

#782 change link to Hackerone to the security form
  SECURITY.md
Labels: enhancement, infrastructure

#786 Fixes deprecation 'Array and string offset access using curly braces'
  core/Logger.php
  htdocs/install/class/xoopsinstallwizard.php
Labels: bug

#787 Fix '0.0.0/composer-include-files 1.5.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.' with newer composer
  composer.lock
Labels: composer

#788 Remove greetings actions due actions/first-interaction#23 bug
  .github/workflows/greetings.yml
Labels: infrastructure
