Repository ImpressCMS/impresscms, pull requests merged in 2020-11, with the labels that each got.

#797 Changed way how paths in subfolder would be handled
  composer.json
  composer.lock
  core/Controllers/LegacyController.php
  core/Extensions/ComposerDefinitions/RoutesComposerDefinition.php
  htdocs/index.php
Labels: bug, enhancement

#802 Upgraded phpunit to 9.4 and test to make sure PHP 8.0 compatible
  .github/workflows/test.yml
  composer.json
  composer.lock
  phpunit.xml
  tests/core/MainfileTest.php
  tests/libraries/icms/AutoloaderTest.php
  tests/libraries/icms/AvatarTest.php
  tests/libraries/icms/CommentTest.php
  tests/libraries/icms/ConfigTest.php
  tests/libraries/icms/DBTest.php
  tests/libraries/icms/DataFileTest.php
  tests/libraries/icms/DebugTest.php
  tests/libraries/icms/EventTest.php
  tests/libraries/icms/FeedsTest.php
  tests/libraries/icms/FilesTest.php
  tests/libraries/icms/FilterTest.php
  tests/libraries/icms/FormTest.php
  tests/libraries/icms/HandlerTest.php
  tests/libraries/icms/ImageTest.php
  tests/libraries/icms/LoggerTest.php
  tests/libraries/icms/MemberTest.php
  tests/libraries/icms/MessageTest.php
  tests/libraries/icms/MessagingTest.php
  tests/libraries/icms/ModuleTest.php
  tests/libraries/icms/NotificationTest.php
  tests/libraries/icms/ObjectTest.php
  tests/libraries/icms/OnlineHandlerTest.php
  tests/libraries/icms/PageTest.php
  tests/libraries/icms/PasswordTest.php
  tests/libraries/icms/PluginsTest.php
  tests/libraries/icms/PreloadTest.php
  tests/libraries/icms/PrivMessageTest.php
  tests/libraries/icms/PropertiesTest.php
  tests/libraries/icms/SecurityTest.php
  tests/libraries/icms/StopSpammerTest.php
  tests/libraries/icms/SysAutotasksTest.php
  tests/libraries/icms/TextsanitizerTest.php
  tests/libraries/icms/UrllinkTest.php
  tests/libraries/icms/UtilsTest.php
  tests/libraries/icms/VersionCheckerTest.php
  tests/libraries/icms/ViewTest.php
Labels: composer, dependencies, enhancement

#719 Checks referers with HTTP middleware instead of security class
  composer.json
  composer.lock
  core/Providers/SecurityServiceProvider.php
  include/constants.php
Labels: composer, enhancement

#806 Include the missing templates for the image manager
  htdocs/editors/FCKeditor/editor/_source/classes/fcktoolbarfontscombo.js
  htdocs/install/class/mainfilemanager.php
  htdocs/install/class/settingmanager.php
  htdocs/install/class/textsanitizer.php
  htdocs/kernel/icmspreloadhandler.php
  htdocs/libraries/icms/form/Base.php
  htdocs/libraries/icms/image/Handler.php
  htdocs/libraries/icms/view/theme/Factory.php
  htdocs/modules/system/icms_version.php
Labels: bug

#810 more strict comparison of variables
  htdocs/libraries/icms/core/Password.php
Labels: bug
