Repository ImpressCMS/impresscms, pull requests merged in 2020-03, with the labels that each got.

#605 add system_adm_modulemenu.html to icms_Version
  htdocs/modules/system/icms_version.php
Labels: bug

#602 Automatic API documentation to Wiki
  .github/workflows/update-wiki.yml
  include/functions.php
  libraries/icms/db/IDatabase.php
  libraries/icms/db/legacy/updater/Handler.php
  libraries/icms/form/elements/captcha/Object.php
  libraries/icms/ipf/Object.php
  libraries/icms/member/rank/Handler.php
  libraries/icms/member/rank/Object.php
  libraries/icms/member/user/Handler.php
  libraries/icms/messaging/Handler.php
  libraries/icms/plugins/Handler.php
  libraries/icms/view/Printerfriendly.php
  libraries/icms/view/block/position/Handler.php
Labels: enhancement, infrastructure

#617 Fixed bug in smarty template touch function
  libraries/icms/view/Tpl.php
Labels: bug

#521 icms_getModuleHandler use container functionality
  include/functions.php
Labels: enhancement

#614 Plug-able module install, update, uninstall functionality + possibility to use module change, activate, deactivate methods not only in web
  core/Providers/DatabaseServiceProvider.php
  core/SetupSteps/Module/Install/AutotasksSetupStep.php
  core/SetupSteps/Module/Install/BlockSetupStep.php
  core/SetupSteps/Module/Install/ConfigSetupStep.php
  core/SetupSteps/Module/Install/ScriptSetupStep.php
  core/SetupSteps/Module/Install/TablesSetupStep.php
  core/SetupSteps/Module/Install/ViewTemplateSetupStep.php
  core/SetupSteps/Module/Uninstall/AutotasksSetupStep.php
  core/SetupSteps/Module/Uninstall/BlockSetupStep.php
  core/SetupSteps/Module/Uninstall/CommentsSetupStep.php
  core/SetupSteps/Module/Uninstall/ConfigSetupStep.php
  core/SetupSteps/Module/Uninstall/DataPageSetupStep.php
  core/SetupSteps/Module/Uninstall/FilesSetupStep.php
  core/SetupSteps/Module/Uninstall/GroupPermissionsSetupStep.php
  core/SetupSteps/Module/Uninstall/NotificationsSetupStep.php
  core/SetupSteps/Module/Uninstall/ScriptSetupStep.php
  core/SetupSteps/Module/Uninstall/TablesSetupStep.php
  core/SetupSteps/Module/Uninstall/UrlLinksSetupStep.php
  core/SetupSteps/Module/Uninstall/ViewTemplateSetupStep.php
  core/SetupSteps/Module/Update/AutotasksSetupStep.php
  core/SetupSteps/Module/Update/BlocksSetupStep.php
  core/SetupSteps/Module/Update/ConfigSetupStep.php
  core/SetupSteps/Module/Update/ScriptSetupStep.php
  core/SetupSteps/Module/Update/ViewTemplateSetupStep.php
  core/SetupSteps/OutputDecorator.php
  core/SetupSteps/SetupStepInterface.php
  libraries/icms.php
  libraries/icms/module/Handler.php
  libraries/icms/view/block/Handler.php
  modules/system/admin/modules.php
  modules/system/admin/modules/modules.php
  modules/system/class/AutotasksHandler.php
  modules/system/language/english/admin/modules.php
Labels: enhancement
