Repository ImpressCMS/impresscms, pull requests merged in 2020-05, with the labels that each got.

#638 quoting the dirname as security improvement
  htdocs/libraries/icms/module/Handler.php
Labels: security vulnerability

#615 Service providers, services and preloads now can be defined in composer.json
  composer.json
  composer.lock
  core/ComposerDefinitions/ComposerDefinitionInterface.php
  core/ComposerDefinitions/ProvidersComposerDefinition.php
  core/ComposerDefinitions/ServicesComposerDefinition.php
  core/Providers/PreloadServiceProvider.php
  libraries/icms.php
  libraries/icms/preload/Handler.php
Labels: composer, enhancement

#618 Container defined editors and sourceeditors
  composer.json
  composer.lock
  htdocs/editors/CKeditor/Editor.php
  htdocs/editors/CKeditor/editor_registry.php
  htdocs/editors/CKeditor/icms_version.php
  htdocs/editors/dhtmltextarea/Editor.php
  htdocs/editors/dhtmltextarea/dhtmltextarea.php
  htdocs/editors/dhtmltextarea/editor_registry.php
  htdocs/editors/tinymce/Editor.php
  htdocs/editors/tinymce/editor_registry.php
  htdocs/editors/tinymce/formtinymce.php
  htdocs/editors/tinymce/icms_version.php
  libraries/icms.php
  libraries/icms/core/Textsanitizer.php
  libraries/icms/form/elements/Dhtmltextarea.php
  libraries/icms/plugins/EditorHandler.php
  libraries/icms/plugins/EditorInterface.php
  plugins/sourceeditors/codemirror/Editor.php
  plugins/sourceeditors/codemirror/editor_registry.php
  plugins/sourceeditors/editarea/Editor.php
  plugins/sourceeditors/editarea/editor_registry.php
  plugins/sourceeditors/editarea/xoops_version.php
Labels: enhancement

#619 Autotask systems registration with container
  composer.json
  composer.lock
  migrations/20200322181415_change_names_for_auto_task_systems_in_config.php
  modules/system/admin/preferences.php
  modules/system/class/AutotasksHandler.php
Labels: enhancement

#621 Installer use same core module functions to install modules as core
  htdocs/install/modulesadmin.php
  htdocs/install/page_modulesinstall.php
Labels: enhancement

#622 Added setup step to copy/update module assets
  composer.json
  composer.lock
  core/Providers/FilesystemServiceProvider.php
  core/SetupSteps/Module/Install/CopyAssetsSetupStep.php
  core/SetupSteps/Module/Uninstall/CopyAssetsSetupStep.php
  core/SetupSteps/Module/Update/CopyAssetsSetupStep.php
  htdocs/install/language/english/welcome.php
  htdocs/install/page_start.php
  htdocs/modules/.gitignore
  modules/system/language/english/admin/modules.php
Labels: enhancement

#627 When property is string with highlighting field correct control will be selected
  libraries/icms/ipf/Object.php
  modules/system/admin/autotasks.php
  modules/system/class/Autotasks.php
Labels: bug

#629 Added console commands support based on symfony/console
  bin/.gitignore
  bin/console
  bin/console.bat
  composer.json
  composer.lock
  core/Commands/CacheClearCommand.php
  core/Commands/ModuleInstallCommand.php
  core/Commands/ModuleUninstallCommand.php
  core/Commands/ModuleUpdateCommand.php
  core/Commands/TemplatesCacheClearCommand.php
  core/ComposerDefinitions/ProvidersComposerDefinition.php
  core/ComposerDefinitions/ServicesComposerDefinition.php
  libraries/icms.php
  libraries/icms/module/Handler.php
  libraries/icms/module/Object.php
Labels: enhancement

#645 Prepare 1.3.12 security release
  docs/changelog.txt
  htdocs/include/version.php
  htdocs/modules/system/icms_version.php
  release_notes.txt
Labels: bug, security vulnerability

#628 Improved bad code handling in autotasks
  modules/system/class/Autotasks.php
Labels: bug, enhancement
