Repository ImpressCMS/impresscms, pull requests merged in 2020-07, with the labels that each got.

#670 Fix blank page after login
  htdocs/modules/system/templates/system_userform.html
Labels: bug

#687 Delete package.json
  htdocs/libraries/jquery/ui/package.json
Labels: enhancement

#625 Fixed image browse multiple default for switch
  modules/system/admin/images/browser.php
Labels: bug, stale

#623 Fixed smarty errors for groups admin page
  htdocs/themes/core/modules/system/admin/groups/system_adm_groups.html
  modules/system/templates/admin/groups/system_adm_groups.html
Labels: bug, stale

#690 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: enhancement, infrastructure

#694 remove the icms_banner reference. No longer present.
  htdocs/include/site-closed.php
  htdocs/libraries/icms/view/theme/Object.php
  htdocs/themes/iTheme/theme.html
  htdocs/themes/iTheme/theme_admin.html
  htdocs/themes/reflex/theme_functions.php
Labels: bug, enhancement

#620 Routes defined in composer.json
  .github/workflows/test.yml
  composer.json
  composer.lock
  core/ComposerDefinitions/RoutesComposerDefinition.php
  core/ComposerDefinitions/ServicesComposerDefinition.php
  core/Controllers/DefaultController.php
  core/Controllers/LegacyController.php
  core/Exceptions/ResponseCodeUnsupportedException.php
  core/Exceptions/RoutePathUndefinedException.php
  core/Response/RedirectResponse.php
  core/Response/ViewResponse.php
  footer.php
  header.php
  htdocs/error.php
  htdocs/index.php
  include/cp_functions.php
  include/functions.php
  libraries/icms.php
  libraries/icms/controller/Handler.php
  libraries/icms/controller/Object.php
  libraries/icms/core/HTMLFilter.php
  libraries/icms/module/Handler.php
  libraries/icms/properties/Handler.php
  libraries/icms/response/DefaultEmptyPage.php
  libraries/icms/response/Error.php
  libraries/icms/response/Events.php
  libraries/icms/response/JSON.php
  libraries/icms/response/JSONP.php
  libraries/icms/response/Serialize.php
  libraries/icms/response/Text.php
  libraries/icms/view/PageBuilder.php
  libraries/icms/view/theme/Object.php
  modules/system/controller/info.php
  phpunit.xml
  tests/bootstrap.php
  tests/libraries/icms/ControllerTest.php
  tests/libraries/icms/ResponseTest.php
Labels: composer, enhancement
