Repository ImpressCMS/impresscms, pull requests merged in 2020-09, with the labels that each got.

#763 Removed old theme functions
  include/old_theme_functions.php
Labels: enhancement

#762 Replace tecnickcom/tcpdf with dompdf/dompdf due license incompatibility
  composer.json
  composer.lock
  include/pdf.php
  language/english/global.php
Labels: bug, composer

#753 Fixes bug when if value in criteria is not a string some comparisons fails
  core/Database/Criteria/CriteriaItem.php
Labels: bug

#756 Replaced mibe/feedwriter with suin/php-rss-writer because of license conflicts
  composer.json
  composer.lock
  core/Data/Feeds/Rss.php
  tests/libraries/icms/FeedsTest.php
Labels: bug, composer

#741 Added PHP 8.0 for tests
  .github/workflows/test.yml
Labels: infrastructure

#755 Composer now has local storage path
  htdocs/install/language/english/welcome.php
  htdocs/install/page_modcheck.php
  htdocs/install/page_modulesinstall.php
  libraries/icms.php
  storage/composer/.gitignore
Labels: bug, composer

#748 Removed todo 'Use language constants for messages' from IPF Handler
  core/Models/AbstractExtendedHandler.php
Labels: bug

#697 sanitizePath in Logger now works faster (caches real path)
  core/Logger.php
Labels: enhancement

#698 there is now a possible way to define required permissions for routes
  core/Extensions/ComposerDefinitions/RoutesComposerDefinition.php
  core/Middlewares/HasGroupMiddleware.php
  core/Middlewares/HasPermissionMiddleware.php
Labels: composer, enhancement

#699 When handling HTTP errors index.php now correctly detects status code
  composer.json
  htdocs/index.php
Labels: bug, composer

#700 Fixes 'Deprecation Notice: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in include/cp_functions.php:277'
  include/cp_functions.php
Labels: bug

#704 Renders legacy routes as groups in cache file
  core/Extensions/ComposerDefinitions/RoutesComposerDefinition.php
Labels: enhancement

#717 Gzip/Deflates encoder based on HTTP Middlewares
  composer.json
  composer.lock
  core/Extensions/ComposerDefinitions/RoutesComposerDefinition.php
  include/common.php
Labels: composer, enhancement

#706 Message confirm screen use build in form elements instead of internally hardcoded HTML elements
  core/Message.php
  core/View/Form/Elements/TrayElement.php
  core/View/Form/ThemeForm.php
Labels: enhancement

#707 Using request middleware for detecting module + tags middleware.global support for all routes
  composer.json
  core/Controllers/LegacyController.php
  core/Extensions/ComposerDefinitions/RoutesComposerDefinition.php
  core/Middlewares/DetectModuleMiddleware.php
  core/Models/AbstractExtendedHandler.php
  core/Providers/ModuleServiceProvider.php
  include/common.php
  libraries/icms.php
  plugins/smarty/function.xoops_link.php
Labels: composer, enhancement

#718 Clears cache when saving config items
  core/Models/ConfigItemHandler.php
Labels: enhancement

#766 correct the interface path for the setupsteps
  core/SetupSteps/Module/Install/CacheClearSetupStep.php
  core/SetupSteps/Module/Uninstall/CacheClearSetupStep.php
  core/SetupSteps/Module/Update/CacheClearSetupStep.php
Labels: bug

#769 Fixed #767: logging into admin gives db error
  core/Models/OnlineHandler.php
Labels: bug

#771 Fixed bug when ImpresCMS was installed in subfolder and route grouping functionality prevendted to add correct prefixes
  composer.lock
  core/Controllers/LegacyController.php
  core/Extensions/ComposerDefinitions/RoutesComposerDefinition.php
  include/constants.php
Labels: bug

#773 Fixed URLs for GPLv2 license in php files
  core/Extensions/Editors/EditorsRegistry.php
  core/View/Form/Elements/Captcha/Image.php
  core/View/Form/Elements/Captcha/ImageMode.php
  core/View/Form/Elements/Captcha/ImageRenderer.php
  core/View/Form/Elements/Captcha/TextMode.php
  core/View/Form/Elements/Captcha/config.php
  core/View/PageBuilder.php
  core/View/Theme/ThemeComponent.php
  core/View/Theme/ThemeFactory.php
  include/findusers.php
  include/site-closed.php
  plugins/smarty/compiler.foreachq.php
  plugins/smarty/compiler.includeq.php
  plugins/smarty/compiler.xoAppUrl.php
  plugins/smarty/compiler.xoImgUrl.php
  plugins/smarty/resource.db.php
  plugins/sourceeditors/codemirror/codemirror.php
  plugins/sourceeditors/editarea/editarea.php
  plugins/sourceeditors/editarea/language/english.php
Labels: bug
