Repository ImpressCMS/impresscms, pull requests merged in 2021-11, with the labels that each got.

#1077 Replaced league router with sunrise http router
  composer.json
  composer.lock
  core/Controllers/DefaultController.php
  core/Controllers/LegacyController.php
  core/Extensions/ComposerDefinitions/ComposerDefinitionInterface.php
  core/Extensions/ComposerDefinitions/ProvidersComposerDefinition.php
  core/Extensions/ComposerDefinitions/RoutesComposerDefinition.php
  core/Extensions/ComposerDefinitions/ServicesComposerDefinition.php
  core/Extensions/SetupSteps/Module/Install/CopyAssetsSetupStep.php
  core/Extensions/SetupSteps/Module/Uninstall/CopyAssetsSetupStep.php
  core/Middlewares/DetectModuleMiddleware.php
  core/Middlewares/HasGroupMiddleware.php
  core/Middlewares/HasPermissionMiddleware.php
  core/Models/ModuleHandler.php
  core/Providers/CacheServiceProvider.php
  core/Providers/FilesystemServiceProvider.php
  core/Providers/RouterServiceProvider.php
  core/Response/ResponseFactory.php
  core/View/Theme/ThemeFactory.php
  htdocs/index.php
  libraries/icms.php
Labels: enhancement

#1078 Add smarty url function
  composer.json
  composer.lock
  core/Providers/RouterServiceProvider.php
  core/Providers/SmartyPluginsProvider.php
Labels: enhancement, dependencies

#1079 Rewrite admin.php as controller
  admin.php
  composer.lock
  core/Controllers/AdminController.php
  core/Data/Feeds/Simplerss.php
  core/Providers/RouterServiceProvider.php
Labels: enhancement

#1080 Misc.php as controller
  composer.lock
  core/Controllers/MiscController.php
  core/File/MediaUploader.php
  core/Models/AvatarHandler.php
  core/Models/OnlineHandler.php
  core/Providers/RouterServiceProvider.php
  core/View/Table/Table.php
  language/english/misc.php
  misc.php
Labels: enhancement

#1084 Fixed legacy url index.php resolving when they are described as paths
  core/Controllers/LegacyController.php
  core/Providers/RouterServiceProvider.php
  htdocs/.htaccess
Labels: bug

#1083 Fixed namespaces issues for never PHP in footer.php and header.php
  footer.php
  header.php
Labels: bug

#966 Added filtering to the input in setSortOrder in icms_ipf_table
  htdocs/include/findusers.php
  htdocs/libraries/icms/ipf/view/Table.php
  htdocs/themes/iTheme/theme_admin.html
Labels: stale

#1082 Move content.php to content module
  composer.lock
  content.php
  core/ModelController.php
  core/Models/AbstractExtendedHandler.php
  core/Providers/RouterServiceProvider.php
  core/Response/ViewResponse.php
  core/View/Theme/ThemeComponent.php
Labels: enhancement

#967 filter url variable in findusers.php
  htdocs/include/findusers.php
  htdocs/libraries/icms/core/DataFilter.php
Labels: bug, security vulnerability

#1086 Fixes crash when not correct order comes from user data for table
  core/View/Table/Table.php
Labels: bug

#1087 Fixes some old class references resolving for some older modules
  include/deprecated_class_aliases.php
Labels: bug

#1091 Fixes system module upgrading from installer
  htdocs/install/page_modulesinstall.php
Labels: bug, installer

#1092 RedirectResponse now can be used for same things as redirect_header
  core/Response/RedirectResponse.php
  include/functions.php
Labels: enhancement

#1093 Remove few system module services that was previously defined in core
  composer.json
Labels: bug
