Repository ImpressCMS/impresscms, pull requests merged in 2021-12, with the labels that each got.

#1101 Add IcmsPersistableController to legacy class resolving map
  include/deprecated_class_aliases.php
Labels: bug

#1102 Fixes few issues with page_modulesinstall.php for installer
  htdocs/install/page_modulesinstall.php
Labels: bug

#1103 Fixed module block titles/names from constants resolving
  core/Extensions/SetupSteps/Module/Install/BlockSetupStep.php
  core/Extensions/SetupSteps/Module/Update/BlocksSetupStep.php
  core/Models/BlockHandler.php
Labels: bug

#1104 Enable migrations for modules in module installer/updating/removing
  composer.json
  core/Extensions/SetupSteps/Module/Install/MigrateSetupStep.php
  core/Extensions/SetupSteps/Module/Update/MigrateSetupStep.php
  phoenix.php
Labels: bug, enhancement

#1105 Added posibility to specify default block weight, position and visibility
  core/Extensions/SetupSteps/Module/Install/BlockSetupStep.php
  core/Extensions/SetupSteps/Module/Update/BlocksSetupStep.php
  migrations/20191230145417_add_initial_data.php
Labels: enhancement

#1107 Fixed incorrect urls for PageNav generated links
  core/View/PageNav.php
Labels: bug

#1108 Add a default parameter to addSlashes
  htdocs/libraries/icms/core/DataFilter.php
Labels: bug
