Repository ImpressCMS/impresscms, pull requests merged in 2021-02, with the labels that each got.

#913 fix vulnerability in autoloader
  htdocs/plugins/preloads/autologin.php
Labels: security vulnerability

#915 block path traversal in image editor, transform .. to _
  htdocs/libraries/image-editor/image-edit.php
Labels: security vulnerability

#917 add install instructions to readme for 2.0
  README.md
Labels: enhancement

#919 Most of Smarty plugins now implemented as composer libraries from @imponeer + xoops_link smarty function removed
  composer.json
  composer.lock
  core/Extensions/Smarty/Blocks/TransBlock.php
  core/Extensions/Smarty/Compiler/ForeachqCloseCompiler.php
  core/Extensions/Smarty/Compiler/ForeachqCompiler.php
  core/Extensions/Smarty/Compiler/IncludeqCompiler.php
  core/Extensions/Smarty/Compiler/XOAppUrlCompiler.php
  core/Extensions/Smarty/Compiler/XOImgUrlCompiler.php
  core/Extensions/Smarty/Functions/ResizeImageFunction.php
  core/Extensions/Smarty/Functions/XOInboxCountFunction.php
  core/Extensions/Smarty/Functions/XOPageNavFunction.php
  core/Extensions/Smarty/Functions/XoopsLinkFunction.php
  core/Extensions/Smarty/Modifiers/DebugPrintVarModifier.php
  core/Extensions/Smarty/Modifiers/TransVarModifier.php
  core/Extensions/Smarty/Resource/DBResource.php
  core/Extensions/Smarty/SmartyBlockExtensionInterface.php
  core/Extensions/Smarty/SmartyCompilerExtensionInterface.php
  core/Extensions/Smarty/SmartyExtensionInterface.php
  core/Extensions/Smarty/SmartyFunctionExtensionInterface.php
  core/Extensions/Smarty/SmartyModifierExtensionInterface.php
  core/Providers/SmartyPluginsProvider.php
  core/View/Template.php
Labels: composer, enhancement
