Repository ImpressCMS/impresscms, pull requests merged in 2022-08, with the labels that each got.

#1260 CI now tries automatically to autofix composer.lock files
  .github/workflows/test-and-autofix.yml
Labels: infrastructure

#1240 Upgrade dompdf to 2.0.0
  composer.json
  composer.lock
Labels: security vulnerability

#1262 Fixes 'Deprecation Notice: rtrim(): Passing null to parameter #1 ($string) of type string is deprecated'
  include/constants.php
Labels: bug
