Repository ImpressCMS/impresscms, pull requests merged in 2022-06, with the labels that each got.

#871 typo: ignore_files -> ignored_files
  .github/workflows/update-wiki.yml
Labels: bug

#1214 Use imponeer/env for env function
  composer.json
  composer.lock
  include/functions.php
Labels: enhancement, dependencies, cleanup

#1223 Updated branch references & readme
  .github/release-drafter.yml
  .github/workflows/apigen.yml
  README.md
Labels: bug, enhancement

#1230 Remove .gitmodules
  .gitmodules
Labels: cleanup
