Repository ImpressCMS/impresscms, pull requests merged in 2022-10, with the labels that each got.

#1311 addPermission now uses 'caption' and 'description' as language strings
  core/Models/AbstractExtendedHandler.php
Labels: bug

#1312 CLI console now uses English as default language
  bin/console
Labels: bug

#1313 Module update CLI command now tries to load module related 'common' and 'modinfo' language files
  core/Commands/ModuleUpdateCommand.php
Labels: bug

#1325 Deprecate addSlashes and stripSlashesGPC functions
  htdocs/install/class/textsanitizer.php
Labels: cleanup

#1314 Fixed filesystem paths
  core/Providers/FilesystemServiceProvider.php
Labels: bug

#1319 Prevents crash when updating module from command line
  core/Extensions/SetupSteps/Module/Update/BlocksSetupStep.php
  core/Models/User.php
Labels: bug

#1321 Fixes DB interfaces incompatibilies between different PHP versions
  htdocs/libraries/icms/db/IConnection.php
Labels: bug

#1322 Fixes DB crash if DB encoding value is empty
  htdocs/libraries/icms/db/Factory.php
Labels: bug

#1323 Fix: notice undefined index utf8 in htdocs/install/page_dbsettings.php on line 138
  htdocs/install/page_dbsettings.php
Labels: bug

#1327 Remove get_magic_quotes_gpc calls
  htdocs/include/functions.php
  htdocs/install/class/textsanitizer.php
  htdocs/libraries/icms/core/DataFilter.php
  htdocs/libraries/icms/file/MediaUploadHandler.php
Labels: bug

#1326 addSlashes and stripSlashesGPC also deprecated in DataFilter
  core/DataFilter.php
Labels: cleanup

#1331 Cookie hardening
  htdocs/include/checklogin.php
  htdocs/include/functions.php
  htdocs/include/im_multilanguage.php
  htdocs/libraries/icms/core/Session.php
  htdocs/libraries/icms/ipf/view/Table.php
  htdocs/modules/system/admin/preferences/main.php
Labels: security vulnerability
