Repository ImpressCMS/impresscms, pull requests merged in 2022-01, with the labels that each got.

#1118 Protector enhancements and added security
  htdocs/install/modules/protector/trust_path/modules/protector/admin/index.php
  htdocs/install/modules/protector/trust_path/modules/protector/class/protector.php
Labels: bug

#1122 Fix GitHub CI Tests + composer.json
  .github/workflows/test.yml
  composer.json
Labels: infrastructure

#1120 smarty upgrade to 4.x
  composer.json
  composer.lock
  core/View/Template.php
Labels: enhancement, dependencies

#1123 Setup steps registered with provider
  composer.json
  core/Providers/SetupStepsProvider.php
Labels: enhancement

#1125 Remove "roave/security-advisories"
  composer.json
  composer.lock
Labels: bug

#1137 Making sure protector gets installed during the site installation
  htdocs/install/page_modulesinstall.php
Labels: bug
